### ISSUE TITLE
Metrics are not available when an unknown device is queried

### ISSUE THREAD

**Issue by shanelilley** [bobrik/kasa_exporter#11]
I have this plugin working, for the most part - it queries the web service and I can see metrics coming back. 
However I see three devices for which perhaps they are old or bad. I get the following error in the debug output and there are no metrics processed and delivered on the http output (the output is blank). 

Wondering if we can add code to bypass bad device and still provide metrics for the successful devices? 

Many thanks,
Shane.

Log below - 

```
< response:
Ok(
    Response {
        error_code: 0,
        message: None,
        result: Some(
            PassthroughResult {
                response_data: "{\"emeter\":{\"get_realtime\":{\"voltage_mv\":247361,\"current_ma\":87,\"power_mw\":8374,\"total_wh\":7453,\"err_code\":0}}}",
            },
        ),
    },
)
< response:
Ok(
    Response {
        error_code: -20103,
        message: Some(
            "The method does not exist or is not available",
        ),
        result: None,
    },
)
error reading device living_room (80198A5E348D26BAE8EA2162EE3B5EB21DFDEB5C): Empty passthrough response
error reading device bedroom (80199FF3B93CFEC815B94748204E587E1DFCEC11): Empty passthrough response
error reading device bedroom (8019D5027139FB9E22DC77F46FEFB3901DFDCDFC): Empty passthrough response
```

**Comment by bobrik** [comment]
This response from your output:

```
< response:
Ok(
    Response {
        error_code: 0,
        message: None,
        result: Some(
            PassthroughResult {
                response_data: "{\"emeter\":{\"get_realtime\":{\"voltage_mv\":247361,\"current_ma\":87,\"power_mw\":8374,\"total_wh\":7453,\"err_code\":0}}}",
            },
        ),
    },
)
```

Looks different from what I have:

```
< response:
Ok(
    Response {
        error_code: 0,
        message: None,
        result: Some(
            PassthroughResult {
                response_data: "{\"emeter\":{\"get_realtime\":{\"current\":0.336662,\"voltage\":122.223768,\"power\":19.802070,\"total\":4.096000,\"err_code\":0}}}",
            },
        ),
    },
)
```

What kind of device do you have?

**Comment by shanelilley** [comment]
Hey!
I have the TP-Link HS110 "smart plugs".

Kind regards,
Shane

**Comment by bobrik** [comment]
Is it a v1 or v2 hardware? What does it say in "Device info" in Kasa app? Here's what I see for mine:

![image](https://user-images.githubusercontent.com/89186/128435397-7f50d102-4bd4-46a0-9192-a4cb3ab20a2f.png)

**Comment by shanelilley** [comment]
Hey Ivan - v2.0 hardware. screen shot below! 

![Screenshot 2021-08-06 at 1 42 19 pm (002)](https://user-images.githubusercontent.com/49427013/128453280-48fe10f7-13be-495a-ad13-a5703aeaba3a.png)

**Comment by bobrik** [comment]
Can you try `ivan/v2-hardware` branch?

**Comment by bobrik** [comment]
This is fixed now.
